### ISSUE TITLE
No plots when running validation with the same datasets

### ISSUE THREAD

**Issue by sheenaze** [awst-austria/qa4sm#157]
When a validation is run with the same dataset (with the same version) used multiple times on the left side there are no plots produced, even if filters are changed for one of the set. The netCDF file exists, it is not empty, but there are no plots. It suggests problem with plotter itself, however should be quickly verified.

**Comment by pstradio** [comment]
Is there no plot image at all in the results folder? I have recently made changes on the plotter function, but I am quite sure that any bugs they might have introduced would still produce the image files. Is this a problem with the production/test or due to the latest merges here?

**Comment by sheenaze** [comment]
You can check on admin panel my last validations, you will see that there are no plots if there is use the same dataset. I don't you spoiled something, because I noticed this issue in my local results from december. The point is, that it doesn't make sense to validate a dataset against itself, so probably no one checked if it works at all :)

**Comment by pstradio** [comment]
I figured out the issue; equal names (same version, same dataset) create a problem with the reader. Rather than a quick fix, I would opt here for a restructuring of the names in the results - this would help also with the summary table and with the validation comparison that I am working on. I will open a new issue that I can work on and refer to this one if that's OK @sheenaze

**Comment by pstradio** [comment]
At a second look we can probably just apply the number prefixes (e.g. 0-Dataset(Version)) everywhere in the plots to just solve this issue, and I will figure out a way to distinguish the two plots in the validation comparison task.

**Comment by pstradio** [comment]
I opened a PR to fix the issue [in the reader](https://github.com/awst-austria/qa4sm-reader/pull/14/files). Please have a look when you have a moment @sheenaze and we can consider this solved
