### ISSUE TITLE
Output file name convention

### ISSUE THREAD

**Issue by pstradio** [awst-austria/qa4sm#183]
The current naming convention for output graphs is a bit overcomplicated for TC metrics, and it could be simplified. This causes the function `get_dataset_combis...` (https://github.com/awst-austria/qa4sm/blob/2026c1ee0ba3b5d2f440d33e20ce6b832a20eb0e/validator/validation/graphics.py#L58) to provide 'fake' ouputs and results in incorrect graph visualization for TC metrics. 
For instance, in [this validation](https://qa4sm.eu/result/6f4b382a-60bc-4296-9b58-d8802a1b12dd/), if we look at the mapplot of SNR (for any variables), the scroll-menu on the right has three entries, and only one is working.

The workaround for this is pretty easy, pretty much just changing the name of the files and the function accordingly. However, it could cause problems with older validations that use the previous convention.

**Comment by sheenaze** [comment]
I established yesterday that we do not need to change these names. Can this issue be closed?
