### ISSUE TITLE
Fix for release 2

### ISSUE THREAD

**Issue by wpreimes** [awst-austria/qa4sm#570]
- [x] Fix bug: Metadata box plots not created when running global ISMN validation
- [x] Doc update: NetCDF example for CSV files missing
- [x] Plot update: Status plots maps (create a single map)
- [x] Update user manual and help page

**Comment by pstradio** [comment]
- [ ] Roll back https://github.com/awst-austria/qa4sm/pull/563 once the SMOS L2 data set has been reprocessed

**Comment by sheenaze** [comment]
- [ ] discuss safety issues
- [ ] verification report
- [ ] mark ISMN as not recommended temporal reference (?)
- [ ] field for spatial lookup

**Comment by wpreimes** [comment]
- [ ] : Release new ISMN version (some stations got lost during parallel metadata collection) and re-generate metadata for all ismn versions on qa4sm.

**Comment by wpreimes** [comment]
- [ ] new release of qa4sm-reader and use in the qa4sm environment
- [ ] new release of qa4sm-preprocessing and use in the qa4sm environment

**Comment by sheenaze** [comment]
We have more and more issues.. maybe we should finally start fixing them...
